## Pivot Tables

This is one of the most powerful tools in pandas to analyze data since it allows you to calculate summary statistics as pivot tables.

Let us try to learn this tool using the following dataset.

https://github.com/plotly/datasets/blob/master/diabetes.csv

In [1]:
import pandas as pd
import numpy as np
D = pd.read_csv("https://raw.githubusercontent.com/plotly/datasets/refs/heads/master/diabetes.csv")
D.info()
D.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [2]:
D.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

#### Fundamentals of a Pandas pivot table.

A pivot table in pandas is a powerful tool for summarizing, analyzing, and transforming data. It allows you to reshape data by organizing it into a two-dimensional table, grouping data by specified rows and columns, and applying an aggregation function to get summary statistics.

https://pandas.pydata.org/docs/reference/api/pandas.pivot_table.html


##### Key Ideas:
- Rows(index): The column(s) used to group the data vertically (usually corresponds to categorical variables).
  * The Index defines the vertical axis of your table. It answers the question: "What do I want to compare?"
- Columns: The column(s) used to group the data horizontally.
  * The Columns define the horizontal axis. It answers the question: "How do I want to segment my comparison?"
- Values: The data to be aggregated, which will fill the cells of the pivot table.
  * The Values are the actual numbers that fill the cells where a Row and a Column intersect.
- Aggregation function: The function applied to the values (e.g., sum(), mean(), count(), etc.) to summarize the data.
  * The Aggfunc (Aggregation Function) is the logic used to squash multiple rows of data into a single number.

In [5]:
pd.pivot_table(D, values="BMI", index='Pregnancies', 
               columns=['Outcome'], aggfunc='mean')

Outcome              0          1
Pregnancies
0            31.727397  39.213158
1            29.616038  37.793103
2            29.679762  34.578947
3            29.231250  32.548148
4            31.255556  33.873913
5            31.100000  36.780952
6            29.591176  31.775000
7            29.975000  34.756000
8            30.693750  32.204545
9            28.840000  33.300000
10           30.114286  31.380000
11           37.125000  39.385714
12           30.560000  34.575000
13           33.280000  36.720000
14                 NaN  35.100000
15                 NaN  37.100000
17                 NaN  40.900000

In [6]:
pd.pivot_table(D, values="BMI", index='Outcome', 
               columns=['Pregnancies'], aggfunc='mean')

Pregnancies,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,17
Outcome,,,,,,,,,,,,,,,,,
0,31.727397,29.616038,29.679762,29.231250,31.255556,31.100000,29.591176,29.975,30.693750,28.84,30.114286,37.125000,30.560,33.28,NaN,NaN,NaN
1,39.213158,37.793103,34.578947,32.548148,33.873913,36.780952,31.775000,34.756,32.204545,33.30,31.380000,39.385714,34.575,36.72,35.1,37.1,40.9

In [11]:
pd.pivot_table(D, values="BloodPressure", index='Outcome', 
               columns=['Pregnancies'], aggfunc='max')

Pregnancies,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,17
Outcome,,,,,,,,,,,,,,,,,
0,100.0,122.0,96.0,100.0,110.0,108.0,96.0,95.0,88.0,80.0,106.0,106.0,85.0,88.0,NaN,NaN,NaN
1,110.0,102.0,90.0,92.0,92.0,108.0,92.0,90.0,106.0,110.0,86.0,94.0,82.0,114.0,78.0,70.0,72.0

In [7]:
pd.pivot_table(D, values=["BMI", "SkinThickness"], index=['Outcome', 'Age'], 
               columns=['Pregnancies', 'Insulin'], aggfunc='mean').head()

                   BMI                                                ...  \
Pregnancies         0                                                 ...
Insulin            0   14    36    40    50    53  63  64    66  72   ...
Outcome Age                                                           ...
0       21   22.385714 NaN   NaN  36.9  30.8   NaN NaN NaN  35.8 NaN  ...
        22   29.000000 NaN  27.8   NaN   NaN   NaN NaN NaN   NaN NaN  ...
        23   26.400000 NaN   NaN   NaN   NaN   NaN NaN NaN   NaN NaN  ...
        24   44.050000 NaN   NaN   NaN   NaN  45.2 NaN NaN   NaN NaN  ...
        25   22.820000 NaN   NaN   NaN   NaN   NaN NaN NaN   NaN NaN  ...

            SkinThickness
Pregnancies            12      13              14      15  17
Insulin               271 325 0   29  110 140 0   184 110 114
Outcome Age
0       21            NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
        22            NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
        23            NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
        24            NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
        25            NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN

[5 rows x 696 columns]

Task:Create a pivot table using the following parameters:
- ```Index```: Pregnancies (This will list $0, 1, 2...$ down the left side).
- ```Columns```: Outcome (This will create two columns at the top: $0$ and $1$).
- ```Values```: ```['BMI', 'Glucose']``` (We want to look at both metrics).
- ```Aggfunc```: 'mean' (We want the average for each group).

In [15]:
pivot = D.pivot_table(
    index='Pregnancies', 
    columns='Outcome', 
    values=['BMI', 'Glucose'], 
    aggfunc=['mean', 'max', 'median']
)

print(exercise_pivot.head())

                  mean                                      max                \
                   BMI                Glucose               BMI       Glucose
Outcome              0          1           0           1     0     1       0
Pregnancies
0            31.727397  39.213158  111.945205  144.236842  52.3  67.1   173.0
1            29.616038  37.793103  104.254717  143.793103  46.3  55.0   193.0
2            29.679762  34.578947  105.214286  135.473684  42.7  45.5   175.0
3            29.231250  32.548148  109.604167  148.444444  57.3  38.4   191.0
4            31.255556  33.873913  117.555556  139.913043  44.5  48.3   197.0

                   median
                      BMI       Glucose
Outcome          1      0     1       0      1
Pregnancies
0            198.0   32.4  37.0   106.0  138.0
1            199.0   28.2  36.5   102.0  133.0
2            197.0   29.7  32.9   105.0  134.0
3            193.0   29.6  33.3   107.0  158.0
4            184.0   31.3  32.3   114.0  142.0